server:
  port: 8808


spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  flyway:
    enabled: true
    locations: classpath:/db/migration
    baseline-on-migrate: true
    sql-migration-suffixes: sql
    baseline-version: 1
  datasource:
    url: jdbc:mariadb://localhost:33306/test?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: user
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
